// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class valr : Exchange
{
    public valr (object args = null): base(args) {}

    public async Task<object> publicGetPairOrderbook (object parameters = null)
    {
        return await this.callAsync ("publicGetPairOrderbook",parameters);
    }

    public async Task<object> publicGetPairOrderbookFull (object parameters = null)
    {
        return await this.callAsync ("publicGetPairOrderbookFull",parameters);
    }

    public async Task<object> publicGetCurrencies (object parameters = null)
    {
        return await this.callAsync ("publicGetCurrencies",parameters);
    }

    public async Task<object> publicGetPairs (object parameters = null)
    {
        return await this.callAsync ("publicGetPairs",parameters);
    }

    public async Task<object> publicGetPairsType (object parameters = null)
    {
        return await this.callAsync ("publicGetPairsType",parameters);
    }

    public async Task<object> publicGetOrdertypes (object parameters = null)
    {
        return await this.callAsync ("publicGetOrdertypes",parameters);
    }

    public async Task<object> publicGetPairOrdertypes (object parameters = null)
    {
        return await this.callAsync ("publicGetPairOrdertypes",parameters);
    }

    public async Task<object> publicGetMarketsummary (object parameters = null)
    {
        return await this.callAsync ("publicGetMarketsummary",parameters);
    }

    public async Task<object> publicGetPairMarketsummary (object parameters = null)
    {
        return await this.callAsync ("publicGetPairMarketsummary",parameters);
    }

    public async Task<object> publicGetPairMarkpriceBuckets (object parameters = null)
    {
        return await this.callAsync ("publicGetPairMarkpriceBuckets",parameters);
    }

    public async Task<object> publicGetPairBuckets (object parameters = null)
    {
        return await this.callAsync ("publicGetPairBuckets",parameters);
    }

    public async Task<object> publicGetPairTrades (object parameters = null)
    {
        return await this.callAsync ("publicGetPairTrades",parameters);
    }

    public async Task<object> publicGetFuturesFundingHistory (object parameters = null)
    {
        return await this.callAsync ("publicGetFuturesFundingHistory",parameters);
    }

    public async Task<object> publicGetFuturesInfo (object parameters = null)
    {
        return await this.callAsync ("publicGetFuturesInfo",parameters);
    }

    public async Task<object> publicGetLoansInfo (object parameters = null)
    {
        return await this.callAsync ("publicGetLoansInfo",parameters);
    }

    public async Task<object> publicGetTime (object parameters = null)
    {
        return await this.callAsync ("publicGetTime",parameters);
    }

    public async Task<object> publicGetStatus (object parameters = null)
    {
        return await this.callAsync ("publicGetStatus",parameters);
    }

    public async Task<object> publicGetRisklimitPair (object parameters = null)
    {
        return await this.callAsync ("publicGetRisklimitPair",parameters);
    }

    public async Task<object> privateGetAccountApiKeysCurrent (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountApiKeysCurrent",parameters);
    }

    public async Task<object> privateGetAccountSubaccounts (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountSubaccounts",parameters);
    }

    public async Task<object> privateGetAccountBalances (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountBalances",parameters);
    }

    public async Task<object> privateGetAccountBalancesAll (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountBalancesAll",parameters);
    }

    public async Task<object> privateGetAccountTransactionhistory (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountTransactionhistory",parameters);
    }

    public async Task<object> privateGetAccountTransactionhistorySubaccounts (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountTransactionhistorySubaccounts",parameters);
    }

    public async Task<object> privateGetAccountPairTradehistory (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountPairTradehistory",parameters);
    }

    public async Task<object> privateGetAccountTradehistory (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountTradehistory",parameters);
    }

    public async Task<object> privateGetAccountFeesTrade (object parameters = null)
    {
        return await this.callAsync ("privateGetAccountFeesTrade",parameters);
    }

    public async Task<object> privateGetMarketdataPairOrderbook (object parameters = null)
    {
        return await this.callAsync ("privateGetMarketdataPairOrderbook",parameters);
    }

    public async Task<object> privateGetMarketdataPairOrderbookFull (object parameters = null)
    {
        return await this.callAsync ("privateGetMarketdataPairOrderbookFull",parameters);
    }

    public async Task<object> privateGetMarketdataPairTradehistory (object parameters = null)
    {
        return await this.callAsync ("privateGetMarketdataPairTradehistory",parameters);
    }

    public async Task<object> privateGetWalletCryptoCurrencyDepositAddress (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoCurrencyDepositAddress",parameters);
    }

    public async Task<object> privateGetWalletCryptoCurrencyDepositHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoCurrencyDepositHistory",parameters);
    }

    public async Task<object> privateGetWalletCryptoDepositHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoDepositHistory",parameters);
    }

    public async Task<object> privateGetWalletCryptoAddressBook (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoAddressBook",parameters);
    }

    public async Task<object> privateGetWalletCryptoAddressBookCurrency (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoAddressBookCurrency",parameters);
    }

    public async Task<object> privateGetWalletCryptoCurrencyWithdraw (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoCurrencyWithdraw",parameters);
    }

    public async Task<object> privateGetWalletCryptoCurrencyWithdrawId (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoCurrencyWithdrawId",parameters);
    }

    public async Task<object> privateGetWalletCryptoCurrencyWithdrawHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoCurrencyWithdrawHistory",parameters);
    }

    public async Task<object> privateGetWalletCryptoWithdrawHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletCryptoWithdrawHistory",parameters);
    }

    public async Task<object> privateGetWalletFiatCurrencyAccountsId (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletFiatCurrencyAccountsId",parameters);
    }

    public async Task<object> privateGetWalletFiatCurrencyAccounts (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletFiatCurrencyAccounts",parameters);
    }

    public async Task<object> privateGetWalletFiatCurrencyBanks (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletFiatCurrencyBanks",parameters);
    }

    public async Task<object> privateGetWalletFiatCurrencyDepositReference (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletFiatCurrencyDepositReference",parameters);
    }

    public async Task<object> privateGetWalletFiatCurrencyDepositReferenceCurrencyBuy (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletFiatCurrencyDepositReferenceCurrencyBuy",parameters);
    }

    public async Task<object> privateGetWalletFiatCurrencyAutoBuy (object parameters = null)
    {
        return await this.callAsync ("privateGetWalletFiatCurrencyAutoBuy",parameters);
    }

    public async Task<object> privateGetSimplePairOrderId (object parameters = null)
    {
        return await this.callAsync ("privateGetSimplePairOrderId",parameters);
    }

    public async Task<object> privateGetPayLimits (object parameters = null)
    {
        return await this.callAsync ("privateGetPayLimits",parameters);
    }

    public async Task<object> privateGetPayPayid (object parameters = null)
    {
        return await this.callAsync ("privateGetPayPayid",parameters);
    }

    public async Task<object> privateGetPayHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetPayHistory",parameters);
    }

    public async Task<object> privateGetPayIdentifierId (object parameters = null)
    {
        return await this.callAsync ("privateGetPayIdentifierId",parameters);
    }

    public async Task<object> privateGetPayTransactionidId (object parameters = null)
    {
        return await this.callAsync ("privateGetPayTransactionidId",parameters);
    }

    public async Task<object> privateGetOrdersPairOrderidId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersPairOrderidId",parameters);
    }

    public async Task<object> privateGetOrdersPairCustomerorderidId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersPairCustomerorderidId",parameters);
    }

    public async Task<object> privateGetOrdersOpen (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersOpen",parameters);
    }

    public async Task<object> privateGetOrdersHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersHistory",parameters);
    }

    public async Task<object> privateGetOrdersHistorySummaryOrderidId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersHistorySummaryOrderidId",parameters);
    }

    public async Task<object> privateGetOrdersHistorySummaryCustomerorderidId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersHistorySummaryCustomerorderidId",parameters);
    }

    public async Task<object> privateGetOrdersHistoryDetailOrderidId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersHistoryDetailOrderidId",parameters);
    }

    public async Task<object> privateGetOrdersHistoryDetailCustomerorderidId (object parameters = null)
    {
        return await this.callAsync ("privateGetOrdersHistoryDetailCustomerorderidId",parameters);
    }

    public async Task<object> privateGetStakingBalancesCurrency (object parameters = null)
    {
        return await this.callAsync ("privateGetStakingBalancesCurrency",parameters);
    }

    public async Task<object> privateGetStakingRates (object parameters = null)
    {
        return await this.callAsync ("privateGetStakingRates",parameters);
    }

    public async Task<object> privateGetStakingRatesCurrency (object parameters = null)
    {
        return await this.callAsync ("privateGetStakingRatesCurrency",parameters);
    }

    public async Task<object> privateGetStakingRewards (object parameters = null)
    {
        return await this.callAsync ("privateGetStakingRewards",parameters);
    }

    public async Task<object> privateGetStakingHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetStakingHistory",parameters);
    }

    public async Task<object> privateGetMarginStatus (object parameters = null)
    {
        return await this.callAsync ("privateGetMarginStatus",parameters);
    }

    public async Task<object> privateGetMarginAccountStatus (object parameters = null)
    {
        return await this.callAsync ("privateGetMarginAccountStatus",parameters);
    }

    public async Task<object> privateGetMarginLeveragePair (object parameters = null)
    {
        return await this.callAsync ("privateGetMarginLeveragePair",parameters);
    }

    public async Task<object> privateGetPositionsOpen (object parameters = null)
    {
        return await this.callAsync ("privateGetPositionsOpen",parameters);
    }

    public async Task<object> privateGetPositionsClosedSummary (object parameters = null)
    {
        return await this.callAsync ("privateGetPositionsClosedSummary",parameters);
    }

    public async Task<object> privateGetPositionsClosed (object parameters = null)
    {
        return await this.callAsync ("privateGetPositionsClosed",parameters);
    }

    public async Task<object> privateGetPositionsHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetPositionsHistory",parameters);
    }

    public async Task<object> privateGetPositionsFundingHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetPositionsFundingHistory",parameters);
    }

    public async Task<object> privateGetBorrowsCurrencyHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetBorrowsCurrencyHistory",parameters);
    }

    public async Task<object> privateGetLoansInfo (object parameters = null)
    {
        return await this.callAsync ("privateGetLoansInfo",parameters);
    }

    public async Task<object> privateGetLoansRates (object parameters = null)
    {
        return await this.callAsync ("privateGetLoansRates",parameters);
    }

    public async Task<object> privateGetLoansRatesHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetLoansRatesHistory",parameters);
    }

    public async Task<object> privateGetLoansOpen (object parameters = null)
    {
        return await this.callAsync ("privateGetLoansOpen",parameters);
    }

    public async Task<object> privateGetLoansCreditHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetLoansCreditHistory",parameters);
    }

    public async Task<object> privateGetLoansUpdateHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetLoansUpdateHistory",parameters);
    }

    public async Task<object> privatePostAccountSubaccount (object parameters = null)
    {
        return await this.callAsync ("privatePostAccountSubaccount",parameters);
    }

    public async Task<object> privatePostAccountSubaccountsTransfer (object parameters = null)
    {
        return await this.callAsync ("privatePostAccountSubaccountsTransfer",parameters);
    }

    public async Task<object> privatePostWalletCryptoCurrencyWithdraw (object parameters = null)
    {
        return await this.callAsync ("privatePostWalletCryptoCurrencyWithdraw",parameters);
    }

    public async Task<object> privatePostWalletCryptoServiceProviders (object parameters = null)
    {
        return await this.callAsync ("privatePostWalletCryptoServiceProviders",parameters);
    }

    public async Task<object> privatePostWalletFiatCurrencyAccounts (object parameters = null)
    {
        return await this.callAsync ("privatePostWalletFiatCurrencyAccounts",parameters);
    }

    public async Task<object> privatePostWalletFiatCurrencyWithdraw (object parameters = null)
    {
        return await this.callAsync ("privatePostWalletFiatCurrencyWithdraw",parameters);
    }

    public async Task<object> privatePostSimplePairQuote (object parameters = null)
    {
        return await this.callAsync ("privatePostSimplePairQuote",parameters);
    }

    public async Task<object> privatePostSimplePairOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostSimplePairOrder",parameters);
    }

    public async Task<object> privatePostPay (object parameters = null)
    {
        return await this.callAsync ("privatePostPay",parameters);
    }

    public async Task<object> privatePostOrdersConditionals (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersConditionals",parameters);
    }

    public async Task<object> privatePostOrdersConditionalsCurrencyPairHistory (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersConditionalsCurrencyPairHistory",parameters);
    }

    public async Task<object> privatePostOrdersConditionalsConditionalPairOrderidId (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersConditionalsConditionalPairOrderidId",parameters);
    }

    public async Task<object> privatePostOrdersLimit (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersLimit",parameters);
    }

    public async Task<object> privatePostOrdersMarket (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersMarket",parameters);
    }

    public async Task<object> privatePostOrdersStopLimit (object parameters = null)
    {
        return await this.callAsync ("privatePostOrdersStopLimit",parameters);
    }

    public async Task<object> privatePostBatchOrders (object parameters = null)
    {
        return await this.callAsync ("privatePostBatchOrders",parameters);
    }

    public async Task<object> privatePostStakingStake (object parameters = null)
    {
        return await this.callAsync ("privatePostStakingStake",parameters);
    }

    public async Task<object> privatePostStakingUnStake (object parameters = null)
    {
        return await this.callAsync ("privatePostStakingUnStake",parameters);
    }

    public async Task<object> privatePostLoans (object parameters = null)
    {
        return await this.callAsync ("privatePostLoans",parameters);
    }

    public async Task<object> privatePutAccountSubaccount (object parameters = null)
    {
        return await this.callAsync ("privatePutAccountSubaccount",parameters);
    }

    public async Task<object> privatePutPayTransactionidIdReverse (object parameters = null)
    {
        return await this.callAsync ("privatePutPayTransactionidIdReverse",parameters);
    }

    public async Task<object> privatePutPayTransactionidIdPartialReverse (object parameters = null)
    {
        return await this.callAsync ("privatePutPayTransactionidIdPartialReverse",parameters);
    }

    public async Task<object> privatePutOrdersModify (object parameters = null)
    {
        return await this.callAsync ("privatePutOrdersModify",parameters);
    }

    public async Task<object> privatePutOrdersConditionalsModify (object parameters = null)
    {
        return await this.callAsync ("privatePutOrdersConditionalsModify",parameters);
    }

    public async Task<object> privatePutMarginAccountStatus (object parameters = null)
    {
        return await this.callAsync ("privatePutMarginAccountStatus",parameters);
    }

    public async Task<object> privatePutMarginLeveragePair (object parameters = null)
    {
        return await this.callAsync ("privatePutMarginLeveragePair",parameters);
    }

    public async Task<object> privatePutLoansIncrease (object parameters = null)
    {
        return await this.callAsync ("privatePutLoansIncrease",parameters);
    }

    public async Task<object> privatePutLoansRate (object parameters = null)
    {
        return await this.callAsync ("privatePutLoansRate",parameters);
    }

    public async Task<object> privatePutLoansUnlock (object parameters = null)
    {
        return await this.callAsync ("privatePutLoansUnlock",parameters);
    }

    public async Task<object> privateDeleteAccountSubaccount (object parameters = null)
    {
        return await this.callAsync ("privateDeleteAccountSubaccount",parameters);
    }

    public async Task<object> privateDeleteWalletFiatCurrencyAccountsId (object parameters = null)
    {
        return await this.callAsync ("privateDeleteWalletFiatCurrencyAccountsId",parameters);
    }

    public async Task<object> privateDeleteOrdersOrder (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrdersOrder",parameters);
    }

    public async Task<object> privateDeleteOrders (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrders",parameters);
    }

    public async Task<object> privateDeleteOrdersPair (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrdersPair",parameters);
    }

    public async Task<object> privateDeleteOrdersConditionals (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrdersConditionals",parameters);
    }

    public async Task<object> privateDeleteOrdersConditionalsPair (object parameters = null)
    {
        return await this.callAsync ("privateDeleteOrdersConditionalsPair",parameters);
    }

    public async Task<object> privateDeleteLoansUnlock (object parameters = null)
    {
        return await this.callAsync ("privateDeleteLoansUnlock",parameters);
    }

    public async Task<object> privateV2GetMarginStatus (object parameters = null)
    {
        return await this.callAsync ("privateV2GetMarginStatus",parameters);
    }

    public async Task<object> privateV2GetHealthz (object parameters = null)
    {
        return await this.callAsync ("privateV2GetHealthz",parameters);
    }

    public async Task<object> privateV2PostOrdersMarket (object parameters = null)
    {
        return await this.callAsync ("privateV2PostOrdersMarket",parameters);
    }

    public async Task<object> privateV2PostOrdersLimit (object parameters = null)
    {
        return await this.callAsync ("privateV2PostOrdersLimit",parameters);
    }

    public async Task<object> privateV2PostOrdersStopLimit (object parameters = null)
    {
        return await this.callAsync ("privateV2PostOrdersStopLimit",parameters);
    }

    public async Task<object> privateV2PutOrdersModify (object parameters = null)
    {
        return await this.callAsync ("privateV2PutOrdersModify",parameters);
    }

    public async Task<object> privateV2DeleteOrdersOrder (object parameters = null)
    {
        return await this.callAsync ("privateV2DeleteOrdersOrder",parameters);
    }

}