// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *ValrCore) PublicGetPairOrderbook (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairOrderbook", args...)
}

func (this *ValrCore) PublicGetPairOrderbookFull (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairOrderbookFull", args...)
}

func (this *ValrCore) PublicGetCurrencies (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetCurrencies", args...)
}

func (this *ValrCore) PublicGetPairs (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairs", args...)
}

func (this *ValrCore) PublicGetPairsType (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairsType", args...)
}

func (this *ValrCore) PublicGetOrdertypes (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetOrdertypes", args...)
}

func (this *ValrCore) PublicGetPairOrdertypes (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairOrdertypes", args...)
}

func (this *ValrCore) PublicGetMarketsummary (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetMarketsummary", args...)
}

func (this *ValrCore) PublicGetPairMarketsummary (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairMarketsummary", args...)
}

func (this *ValrCore) PublicGetPairMarkpriceBuckets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairMarkpriceBuckets", args...)
}

func (this *ValrCore) PublicGetPairBuckets (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairBuckets", args...)
}

func (this *ValrCore) PublicGetPairTrades (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetPairTrades", args...)
}

func (this *ValrCore) PublicGetFuturesFundingHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetFuturesFundingHistory", args...)
}

func (this *ValrCore) PublicGetFuturesInfo (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetFuturesInfo", args...)
}

func (this *ValrCore) PublicGetLoansInfo (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetLoansInfo", args...)
}

func (this *ValrCore) PublicGetTime (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetTime", args...)
}

func (this *ValrCore) PublicGetStatus (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetStatus", args...)
}

func (this *ValrCore) PublicGetRisklimitPair (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetRisklimitPair", args...)
}

func (this *ValrCore) PrivateGetAccountApiKeysCurrent (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountApiKeysCurrent", args...)
}

func (this *ValrCore) PrivateGetAccountSubaccounts (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountSubaccounts", args...)
}

func (this *ValrCore) PrivateGetAccountBalances (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountBalances", args...)
}

func (this *ValrCore) PrivateGetAccountBalancesAll (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountBalancesAll", args...)
}

func (this *ValrCore) PrivateGetAccountTransactionhistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountTransactionhistory", args...)
}

func (this *ValrCore) PrivateGetAccountTransactionhistorySubaccounts (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountTransactionhistorySubaccounts", args...)
}

func (this *ValrCore) PrivateGetAccountPairTradehistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountPairTradehistory", args...)
}

func (this *ValrCore) PrivateGetAccountTradehistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountTradehistory", args...)
}

func (this *ValrCore) PrivateGetAccountFeesTrade (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetAccountFeesTrade", args...)
}

func (this *ValrCore) PrivateGetMarketdataPairOrderbook (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetMarketdataPairOrderbook", args...)
}

func (this *ValrCore) PrivateGetMarketdataPairOrderbookFull (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetMarketdataPairOrderbookFull", args...)
}

func (this *ValrCore) PrivateGetMarketdataPairTradehistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetMarketdataPairTradehistory", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoCurrencyDepositAddress (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoCurrencyDepositAddress", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoCurrencyDepositHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoCurrencyDepositHistory", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoDepositHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoDepositHistory", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoAddressBook (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoAddressBook", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoAddressBookCurrency (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoAddressBookCurrency", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoCurrencyWithdraw (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoCurrencyWithdraw", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoCurrencyWithdrawId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoCurrencyWithdrawId", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoCurrencyWithdrawHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoCurrencyWithdrawHistory", args...)
}

func (this *ValrCore) PrivateGetWalletCryptoWithdrawHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletCryptoWithdrawHistory", args...)
}

func (this *ValrCore) PrivateGetWalletFiatCurrencyAccountsId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletFiatCurrencyAccountsId", args...)
}

func (this *ValrCore) PrivateGetWalletFiatCurrencyAccounts (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletFiatCurrencyAccounts", args...)
}

func (this *ValrCore) PrivateGetWalletFiatCurrencyBanks (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletFiatCurrencyBanks", args...)
}

func (this *ValrCore) PrivateGetWalletFiatCurrencyDepositReference (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletFiatCurrencyDepositReference", args...)
}

func (this *ValrCore) PrivateGetWalletFiatCurrencyDepositReferenceCurrencyBuy (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletFiatCurrencyDepositReferenceCurrencyBuy", args...)
}

func (this *ValrCore) PrivateGetWalletFiatCurrencyAutoBuy (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetWalletFiatCurrencyAutoBuy", args...)
}

func (this *ValrCore) PrivateGetSimplePairOrderId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetSimplePairOrderId", args...)
}

func (this *ValrCore) PrivateGetPayLimits (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPayLimits", args...)
}

func (this *ValrCore) PrivateGetPayPayid (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPayPayid", args...)
}

func (this *ValrCore) PrivateGetPayHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPayHistory", args...)
}

func (this *ValrCore) PrivateGetPayIdentifierId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPayIdentifierId", args...)
}

func (this *ValrCore) PrivateGetPayTransactionidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPayTransactionidId", args...)
}

func (this *ValrCore) PrivateGetOrdersPairOrderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersPairOrderidId", args...)
}

func (this *ValrCore) PrivateGetOrdersPairCustomerorderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersPairCustomerorderidId", args...)
}

func (this *ValrCore) PrivateGetOrdersOpen (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersOpen", args...)
}

func (this *ValrCore) PrivateGetOrdersHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersHistory", args...)
}

func (this *ValrCore) PrivateGetOrdersHistorySummaryOrderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersHistorySummaryOrderidId", args...)
}

func (this *ValrCore) PrivateGetOrdersHistorySummaryCustomerorderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersHistorySummaryCustomerorderidId", args...)
}

func (this *ValrCore) PrivateGetOrdersHistoryDetailOrderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersHistoryDetailOrderidId", args...)
}

func (this *ValrCore) PrivateGetOrdersHistoryDetailCustomerorderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetOrdersHistoryDetailCustomerorderidId", args...)
}

func (this *ValrCore) PrivateGetStakingBalancesCurrency (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetStakingBalancesCurrency", args...)
}

func (this *ValrCore) PrivateGetStakingRates (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetStakingRates", args...)
}

func (this *ValrCore) PrivateGetStakingRatesCurrency (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetStakingRatesCurrency", args...)
}

func (this *ValrCore) PrivateGetStakingRewards (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetStakingRewards", args...)
}

func (this *ValrCore) PrivateGetStakingHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetStakingHistory", args...)
}

func (this *ValrCore) PrivateGetMarginStatus (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetMarginStatus", args...)
}

func (this *ValrCore) PrivateGetMarginAccountStatus (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetMarginAccountStatus", args...)
}

func (this *ValrCore) PrivateGetMarginLeveragePair (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetMarginLeveragePair", args...)
}

func (this *ValrCore) PrivateGetPositionsOpen (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPositionsOpen", args...)
}

func (this *ValrCore) PrivateGetPositionsClosedSummary (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPositionsClosedSummary", args...)
}

func (this *ValrCore) PrivateGetPositionsClosed (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPositionsClosed", args...)
}

func (this *ValrCore) PrivateGetPositionsHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPositionsHistory", args...)
}

func (this *ValrCore) PrivateGetPositionsFundingHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetPositionsFundingHistory", args...)
}

func (this *ValrCore) PrivateGetBorrowsCurrencyHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetBorrowsCurrencyHistory", args...)
}

func (this *ValrCore) PrivateGetLoansInfo (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetLoansInfo", args...)
}

func (this *ValrCore) PrivateGetLoansRates (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetLoansRates", args...)
}

func (this *ValrCore) PrivateGetLoansRatesHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetLoansRatesHistory", args...)
}

func (this *ValrCore) PrivateGetLoansOpen (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetLoansOpen", args...)
}

func (this *ValrCore) PrivateGetLoansCreditHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetLoansCreditHistory", args...)
}

func (this *ValrCore) PrivateGetLoansUpdateHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetLoansUpdateHistory", args...)
}

func (this *ValrCore) PrivatePostAccountSubaccount (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostAccountSubaccount", args...)
}

func (this *ValrCore) PrivatePostAccountSubaccountsTransfer (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostAccountSubaccountsTransfer", args...)
}

func (this *ValrCore) PrivatePostWalletCryptoCurrencyWithdraw (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostWalletCryptoCurrencyWithdraw", args...)
}

func (this *ValrCore) PrivatePostWalletCryptoServiceProviders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostWalletCryptoServiceProviders", args...)
}

func (this *ValrCore) PrivatePostWalletFiatCurrencyAccounts (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostWalletFiatCurrencyAccounts", args...)
}

func (this *ValrCore) PrivatePostWalletFiatCurrencyWithdraw (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostWalletFiatCurrencyWithdraw", args...)
}

func (this *ValrCore) PrivatePostSimplePairQuote (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostSimplePairQuote", args...)
}

func (this *ValrCore) PrivatePostSimplePairOrder (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostSimplePairOrder", args...)
}

func (this *ValrCore) PrivatePostPay (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostPay", args...)
}

func (this *ValrCore) PrivatePostOrdersConditionals (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersConditionals", args...)
}

func (this *ValrCore) PrivatePostOrdersConditionalsCurrencyPairHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersConditionalsCurrencyPairHistory", args...)
}

func (this *ValrCore) PrivatePostOrdersConditionalsConditionalPairOrderidId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersConditionalsConditionalPairOrderidId", args...)
}

func (this *ValrCore) PrivatePostOrdersLimit (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersLimit", args...)
}

func (this *ValrCore) PrivatePostOrdersMarket (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersMarket", args...)
}

func (this *ValrCore) PrivatePostOrdersStopLimit (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostOrdersStopLimit", args...)
}

func (this *ValrCore) PrivatePostBatchOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostBatchOrders", args...)
}

func (this *ValrCore) PrivatePostStakingStake (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostStakingStake", args...)
}

func (this *ValrCore) PrivatePostStakingUnStake (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostStakingUnStake", args...)
}

func (this *ValrCore) PrivatePostLoans (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostLoans", args...)
}

func (this *ValrCore) PrivatePutAccountSubaccount (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutAccountSubaccount", args...)
}

func (this *ValrCore) PrivatePutPayTransactionidIdReverse (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutPayTransactionidIdReverse", args...)
}

func (this *ValrCore) PrivatePutPayTransactionidIdPartialReverse (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutPayTransactionidIdPartialReverse", args...)
}

func (this *ValrCore) PrivatePutOrdersModify (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutOrdersModify", args...)
}

func (this *ValrCore) PrivatePutOrdersConditionalsModify (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutOrdersConditionalsModify", args...)
}

func (this *ValrCore) PrivatePutMarginAccountStatus (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutMarginAccountStatus", args...)
}

func (this *ValrCore) PrivatePutMarginLeveragePair (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutMarginLeveragePair", args...)
}

func (this *ValrCore) PrivatePutLoansIncrease (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutLoansIncrease", args...)
}

func (this *ValrCore) PrivatePutLoansRate (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutLoansRate", args...)
}

func (this *ValrCore) PrivatePutLoansUnlock (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutLoansUnlock", args...)
}

func (this *ValrCore) PrivateDeleteAccountSubaccount (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteAccountSubaccount", args...)
}

func (this *ValrCore) PrivateDeleteWalletFiatCurrencyAccountsId (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteWalletFiatCurrencyAccountsId", args...)
}

func (this *ValrCore) PrivateDeleteOrdersOrder (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrdersOrder", args...)
}

func (this *ValrCore) PrivateDeleteOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrders", args...)
}

func (this *ValrCore) PrivateDeleteOrdersPair (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrdersPair", args...)
}

func (this *ValrCore) PrivateDeleteOrdersConditionals (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrdersConditionals", args...)
}

func (this *ValrCore) PrivateDeleteOrdersConditionalsPair (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteOrdersConditionalsPair", args...)
}

func (this *ValrCore) PrivateDeleteLoansUnlock (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteLoansUnlock", args...)
}

func (this *ValrCore) PrivateV2GetMarginStatus (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2GetMarginStatus", args...)
}

func (this *ValrCore) PrivateV2GetHealthz (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2GetHealthz", args...)
}

func (this *ValrCore) PrivateV2PostOrdersMarket (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2PostOrdersMarket", args...)
}

func (this *ValrCore) PrivateV2PostOrdersLimit (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2PostOrdersLimit", args...)
}

func (this *ValrCore) PrivateV2PostOrdersStopLimit (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2PostOrdersStopLimit", args...)
}

func (this *ValrCore) PrivateV2PutOrdersModify (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2PutOrdersModify", args...)
}

func (this *ValrCore) PrivateV2DeleteOrdersOrder (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateV2DeleteOrdersOrder", args...)
}
